name: Test Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno test test/test.ts
